apiVersion: apps/v1
kind: Deployment
metadata:
  name: housedb-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: housedb-backend
  template:
    metadata:
      labels:
        app: housedb-backend
    spec:
      containers:
        - name: housedb-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
{{ toYaml .Values.resources | indent 12 }}
