{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "housedb-backend.fullname" . }}
  labels:
    {{- include "housedb-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_URL: {{ .Values.secretEnv.DB_URL | quote }}
  DB_USER: {{ .Values.secretEnv.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secretEnv.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secretEnv.JWT_SECRET | quote }}
  KIWI_APP_CLIENT_ID: {{ .Values.secretEnv.KIWI_APP_CLIENT_ID | quote }}
  KIWI_APP_CLIENT_SECRET: {{ .Values.secretEnv.KIWI_APP_CLIENT_SECRET | quote }}
  KIWI_ADMIN_USERNAME: {{ .Values.secretEnv.KIWI_ADMIN_USERNAME | quote }}
  KIWI_ADMIN_PASSWORD: {{ .Values.secretEnv.KIWI_ADMIN_PASSWORD | quote }}
{{- end }}
