apiVersion: v1
kind: Service
metadata:
  name: housedb-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: housedb-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
