apiVersion: v1
kind: Service
metadata:
  name: {{ include "housedb-backend.fullname" . }}
  labels:
    {{- include "housedb-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.exposeGlowroot }}
    - port: {{ .Values.service.glowrootPort }}
      targetPort: glowroot
      protocol: TCP
      name: glowroot
    {{- end }}
  selector:
    {{- include "housedb-backend.selectorLabels" . | nindent 4 }}
